spring.application.name=sales-management

jwt.secret=${JWT_SECRET}
jwt.access-token-expiry-ms=120000
jwt.refresh-token-expiry-ms=604800000
spring.flyway.out-of-order=true

spring.flyway.locations=classpath:db/migration,classpath:db/seeder

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

epod.upload-dir=./epod-uploads
epod.storage-dir=./epod-storage

#company coordinates
company.latitude=33.3583
company.longitude=36.2417