spring.application.name=sales-management

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=900000
jwt.refresh-expiration-ms=604800000
spring.flyway.out-of-order=true

spring.flyway.locations=classpath:db/migration,classpath:db/seeder