-- src/main/resources/db/migration/invoicing/V10__create_invoicing_tables.sql

-- ─────────────────────────────────────────────────────────────────────────
-- INVOICING: digital sales invoices raised by reps in the field, reviewed by
-- sales managers. Owned by the `invoicing` module.
--
-- One migration, three tables, applied atomically. Order matters: the header
-- (invoices) is created before its children (invoice_line_items, epod_artifacts).
--
-- Cross-module FKs declared HERE because the DEPENDENT module owns them:
--   * invoices.customer_id                     -> customer.customers(id)
--   * invoices.representative_id,
--     invoices.reviewed_by_id                  -> identity.users(id)
--   * invoices.visit_id                        -> visit.visits(id)   [nullable]
--   * invoice_line_items.product_id            -> inventory.products(id)
-- Role conditions (SALES_REP creates/submits; SALES_MANAGER or ADMIN reviews)
-- are enforced in the application layer (InvoiceService via UserFacade /
-- @PreAuthorize); a DB FK cannot express a role.
--
-- Flyway versions are GLOBALLY unique across all module subdirectories:
--   V0 modulith · V1,V2 identity · V3 territory · V4 customer ·
--   V5 inventory · V6 vanops · V7,V7_1 routing · V8 visit ·
--   V9 event_publication patch · V10 invoicing (this file).
--
-- Design decisions encoded here (see invoicing_V10_decisions.md):
--   D1  stock deducts at submit (app layer); no schema hook needed
--   D2  rejection_reason column (non-blank guard is app-layer, on reject)
--   D3  reviewed_by_id column; review timestamp reuses updated_at
--   D6  status set DRAFT | SENT | APPROVED | REJECTED (CHECK)
--   D8  no tax column; total_amount = sum(line subtotals)
--   D9  money as NUMERIC(12,2)
--   D11 UNIQUE(invoice_id, product_id) on lines
--   D12 no product-active CHECK; discontinued stock may still be sold
--   D13 visit_id NULLABLE
--   D16 epod_artifacts child table (signature + delivery photo), url + hash + gps
--   D22 client_uuid UNIQUE for offline-submit idempotency
-- ─────────────────────────────────────────────────────────────────────────


-- ===== INVOICES (header) =================================================
CREATE TABLE invoices (
                          id                 BIGSERIAL      PRIMARY KEY,

    -- Cross-module references (plain FK ids; no JPA object references).
                          customer_id        BIGINT         NOT NULL,
                          representative_id  BIGINT         NOT NULL,
                          visit_id           BIGINT         NULL,      -- D13: invoice may exist with no visit

    -- Business date of the sale. Server-set online (LocalDate.now); client-set on sync (D15).
                          invoice_date       DATE           NOT NULL,

    -- D9: fixed-point money. Server-recomputed; client totals ignored.
                          total_amount       NUMERIC(12,2)  NOT NULL,

                          status             VARCHAR(30)    NOT NULL,

    -- D2 / D3: review outcome. All NULL until a manager acts.
                          rejection_reason   TEXT           NULL,
                          reviewed_by_id     BIGINT         NULL,

    -- D22: idempotency key generated by the mobile app before sending, so a
    -- retried offline submit is recognised and skipped. NULL for rows created
    -- via the online path (no retry-duplication risk there).
                          client_uuid        VARCHAR(36)    NULL,

                          created_at         TIMESTAMPTZ    NOT NULL,
                          updated_at         TIMESTAMPTZ    NOT NULL,

                          CONSTRAINT fk_invoices_customer
                              FOREIGN KEY (customer_id)       REFERENCES customers (id),
                          CONSTRAINT fk_invoices_representative
                              FOREIGN KEY (representative_id)  REFERENCES users (id),
                          CONSTRAINT fk_invoices_visit
                              FOREIGN KEY (visit_id)          REFERENCES visits (id),
                          CONSTRAINT fk_invoices_reviewed_by
                              FOREIGN KEY (reviewed_by_id)    REFERENCES users (id),

                          CONSTRAINT chk_invoices_status
                              CHECK (status IN ('DRAFT', 'SENT', 'APPROVED', 'REJECTED')),

    -- Money is never negative.
                          CONSTRAINT chk_invoices_total_amount
                              CHECK (total_amount >= 0),

    -- D22: one invoice per client-generated uuid. NULLs are allowed and are not
    -- considered equal by Postgres, so multiple online (NULL) rows coexist.
                          CONSTRAINT uq_invoices_client_uuid
                              UNIQUE (client_uuid)
);

CREATE INDEX idx_invoices_representative ON invoices (representative_id);
CREATE INDEX idx_invoices_customer       ON invoices (customer_id);
CREATE INDEX idx_invoices_status         ON invoices (status);
CREATE INDEX idx_invoices_invoice_date   ON invoices (invoice_date);
-- visit_id / reviewed_by_id are sparse (nullable, low-cardinality use); indexed
-- for the FK integrity check and occasional lookups.
CREATE INDEX idx_invoices_visit          ON invoices (visit_id);
CREATE INDEX idx_invoices_reviewed_by    ON invoices (reviewed_by_id);

COMMENT ON TABLE  invoices                   IS 'Sales invoices. Rep raises DRAFT, submits to SENT (stock deducts atomically), manager APPROVES or REJECTS (informational in MVP).';
COMMENT ON COLUMN invoices.customer_id       IS 'FK to customers.id. Must be ACTIVE at submit (enforced in app layer).';
COMMENT ON COLUMN invoices.representative_id IS 'FK to users.id. The creating SALES_REP; taken from the principal, never the request body (BR-1).';
COMMENT ON COLUMN invoices.visit_id          IS 'FK to visits.id. NULLABLE — an invoice may be an ad-hoc/off-route sale with no visit (SRS alt-flow 4A).';
COMMENT ON COLUMN invoices.invoice_date      IS 'Business date of the sale (LocalDate). Server-set online; client-supplied on offline sync.';
COMMENT ON COLUMN invoices.total_amount      IS 'Server-recomputed sum of line subtotals, NUMERIC(12,2). Client-sent totals are ignored.';
COMMENT ON COLUMN invoices.status            IS 'Lifecycle: DRAFT (editable, no stock moved) -> SENT (immutable, stock deducted) -> APPROVED | REJECTED (terminal).';
COMMENT ON COLUMN invoices.rejection_reason  IS 'Mandatory non-blank reason when status = REJECTED (BR-3); NULL otherwise. Guard in app layer.';
COMMENT ON COLUMN invoices.reviewed_by_id    IS 'FK to users.id — the SALES_MANAGER or ADMIN who approved/rejected. NULL until reviewed. Review time = updated_at.';
COMMENT ON COLUMN invoices.client_uuid       IS 'Mobile-generated idempotency key (UUID). Deduplicates retried offline submits. NULL for online-created invoices.';


-- ===== INVOICE_LINE_ITEMS ================================================
CREATE TABLE invoice_line_items (
                          id            BIGSERIAL      PRIMARY KEY,
                          invoice_id    BIGINT         NOT NULL,
                          product_id    BIGINT         NOT NULL,

                          quantity      INTEGER        NOT NULL,

    -- D10 / BR-9: unit price captured from inventory, frozen at submit.
                          price         NUMERIC(12,2)  NOT NULL,
    -- D7: single line-level fixed-amount discount.
                          discount      NUMERIC(12,2)  NOT NULL DEFAULT 0,
    -- D9: server-computed = quantity * price - discount.
                          subtotal      NUMERIC(12,2)  NOT NULL,

                          created_at    TIMESTAMPTZ    NOT NULL,
                          updated_at    TIMESTAMPTZ    NOT NULL,

                          CONSTRAINT fk_invoice_line_items_invoice
                              FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE,
                          CONSTRAINT fk_invoice_line_items_product
                              FOREIGN KEY (product_id) REFERENCES products (id),

    -- D11: one line per (invoice, product) — no two lines for the same product.
                          CONSTRAINT uq_invoice_line_items_invoice_product
                              UNIQUE (invoice_id, product_id),

    -- D12: quantity positive. NB: no product-active check — discontinued stock
    -- physically on the van may still be sold.
                          CONSTRAINT chk_invoice_line_items_quantity
                              CHECK (quantity > 0),
    -- D7: discount within [0, quantity * price]; subtotal never negative.
                          CONSTRAINT chk_invoice_line_items_price
                              CHECK (price >= 0),
                          CONSTRAINT chk_invoice_line_items_discount
                              CHECK (discount >= 0 AND discount <= price * quantity),
                          CONSTRAINT chk_invoice_line_items_subtotal
                              CHECK (subtotal >= 0)
);

-- invoice_id is the LEADING column of uq_invoice_line_items_invoice_product,
-- so that unique index already covers FK integrity and "all lines of an invoice"
-- lookups. product_id needs its own index for the product-side FK check.
CREATE INDEX idx_invoice_line_items_product ON invoice_line_items (product_id);

COMMENT ON TABLE  invoice_line_items            IS 'Line items of an invoice: product, quantity, captured unit price, fixed discount, computed subtotal.';
COMMENT ON COLUMN invoice_line_items.product_id IS 'FK to products.id.';
COMMENT ON COLUMN invoice_line_items.quantity   IS 'Units sold (> 0).';
COMMENT ON COLUMN invoice_line_items.price      IS 'Unit price captured from inventory, re-read on each DRAFT edit, frozen at submit (BR-9).';
COMMENT ON COLUMN invoice_line_items.discount   IS 'Line-level fixed-amount discount (0..price*quantity). Percentages are converted client-side before POST.';
COMMENT ON COLUMN invoice_line_items.subtotal   IS 'Server-computed quantity*price - discount, NUMERIC(12,2). Client-sent value ignored.';


-- ===== EPOD_ARTIFACTS ====================================================
-- Electronic Proof of Delivery. One invoice -> many artifacts (signature +
-- delivery photo now; goods photo etc. later with no schema change). Each row
-- stores a pointer to a file on disk (url), a tamper-detection hash binding the
-- file to this invoice's identity data, plus the GPS location where it was
-- captured. All artifacts are captured/frozen at submit and never mutated.
CREATE TABLE epod_artifacts (
                          id            BIGSERIAL      PRIMARY KEY,
                          invoice_id    BIGINT         NOT NULL,

    -- SIGNATURE | DELIVERY_PHOTO (extensible: GOODS_PHOTO, ... later).
                          type          VARCHAR(30)    NOT NULL,

    -- Pointer to the stored file (write-once path, e.g. signatures/invoice_{id}.png).
                          url           TEXT           NOT NULL,
    -- SHA-256(invoice identity data + file bytes). Computed server-side at submit;
    -- welds this file to this invoice so it cannot be reused elsewhere.
                          hash          VARCHAR(64)    NOT NULL,

    -- D16: where this artifact was captured (rep's device at capture time).
                          latitude      NUMERIC(9,6)   NULL,
                          longitude     NUMERIC(9,6)   NULL,

    -- Proof timestamp. Instant (UTC); client sends ISO 8601 with offset on sync.
                          captured_at   TIMESTAMPTZ    NOT NULL,

                          created_at    TIMESTAMPTZ    NOT NULL,
                          updated_at    TIMESTAMPTZ    NOT NULL,

                          CONSTRAINT fk_epod_artifacts_invoice
                              FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE,

                          CONSTRAINT chk_epod_artifacts_type
                              CHECK (type IN ('SIGNATURE', 'DELIVERY_PHOTO')),

    -- Both mandatory artifacts appear at most once per invoice.
                          CONSTRAINT uq_epod_artifacts_invoice_type
                              UNIQUE (invoice_id, type)
);

CREATE INDEX idx_epod_artifacts_invoice ON epod_artifacts (invoice_id);

COMMENT ON TABLE  epod_artifacts             IS 'Electronic Proof of Delivery artifacts (signature, delivery photo) for an invoice. Captured and frozen at submit.';
COMMENT ON COLUMN epod_artifacts.invoice_id  IS 'FK to invoices.id.';
COMMENT ON COLUMN epod_artifacts.type        IS 'Artifact type: SIGNATURE (customer-drawn) or DELIVERY_PHOTO. Extensible.';
COMMENT ON COLUMN epod_artifacts.url         IS 'Pointer to the file on disk (object-store-style). The row never stores the bytes.';
COMMENT ON COLUMN epod_artifacts.hash        IS 'SHA-256(invoiceId + customerId + total + file bytes). Server-computed at submit; detects tampering / reuse.';
COMMENT ON COLUMN epod_artifacts.latitude    IS 'GPS latitude where the artifact was captured (NUMERIC(9,6)); may be NULL.';
COMMENT ON COLUMN epod_artifacts.longitude   IS 'GPS longitude where the artifact was captured (NUMERIC(9,6)); may be NULL.';
COMMENT ON COLUMN epod_artifacts.captured_at IS 'UTC instant the artifact was captured. Client sends ISO 8601 with explicit offset on sync.';
